### ISSUE TITLE
how long for training 

### ISSUE THREAD

**Issue by bansky-cl** [lvyiwei1/DiffuSeq_StylePTB#1]
good job and plenty experiments!
It may need 2days in 8*A100 80G that i see in diffuseq, so i would like to know how long you train in so many experiments.

**Comment by lvyiwei1** [comment]
Thank you for your interest in our research (and sorry for replying late)! In our largest experiment (multitask training of all individual transfers), we trained the model on 4 A40 GPUs for about 1.5 days. For the individual transfers without multitask, training each model takes 0.5-1 days on 4 A40 GPUs depending on the data size.
